### PR TITLE
introspection: finish support for schema aware introspection

### PR DESCRIPTION
**Pull request by bdauvergne**
Query to pg_catalog tables are joined with pg_namespace.name =
self.connection.schema_name and queries to the information_schema schema get
the clause table_schema = self.connectin.schema_name.

### CODE REVIEW

**Comment by bdauvergne** [comment]
It should fix problem with migration altering foreign key fields on Django 1.7.7 (before Django 1.7.6 it just does not work).

**Comment by bdauvergne** [comment]
I fixed the namespace name accessor (nspname instead of name).

**Comment by bernardopires** [comment]
Hi @bdauvergne, does the problem still exist on the latest version of dts? Thanks!

**Comment by bdauvergne** [comment]
I think the problem still exist with Django 1.7.x but I don't know it is a target for you.

**Comment by bdauvergne** [comment]
Reading my patch and what was done for 1.8 support I'm pretty sure migrations does not work with Django 1.8 and tenant_schemas when modifying indexes for example. Only get_table_list() is implemented but there are many more methods in the DatabaseSchemaIntrospection class.

**Pull request closed without merging**
