### PR TITLE
Parallel migrations

### PR DESCRIPTION
**Pull request by mcanaves**
Added multiprocess migration option which use parallel processes to speed up the migration as mentioned on #387 . It's a transposition of django-tenants solution.

PS: clean version of my chaotic pr #391 wich fix issues #387 and #415. Implements @AlexvEck suggested changes in pr #391.

### CODE REVIEW

**Comment by stephane** [comment]
@AlexvEck so we can close #422, can't we?

**Comment by AlexvEck** [comment]
@stephane yes we can :)

**Comment by xgilest** [comment]
@goodtune @bernardopires Hi, how are you doing? Is there anything we can do to help you review the PR, thank you.

**Comment by mcanaves** [comment]
Conflicts resolved @bernardopires @goodtune.

**Comment by Leeaandrob** [comment]
Could you update the documentation about this feature? @bernardopires @mcanaves

**Comment by mcanaves** [comment]
@Leeaandrob you can find the documentation about this feature [here](http://django-tenant-schemas.readthedocs.io/en/latest/use.html#migrate-schemas-in-parallel)

**Pull request merged**
