### PR TITLE
Django 1.7 support

### LINKED ISSUE #134: Django 1.7 migrations support
Django 1.7 about to be released adds core support for migrations instead of South. This app alters the functionality of `syncdb` and a couple of South's `manage.py` commands which will no longer be applicable >=Django 1.7. Any plans to support 1.7?

### PR DESCRIPTION
**Pull request by owais**
Initial support for django 1.7. Fixes #134

### CODE REVIEW

**Comment by bernardopires** [comment]
@owais, thank you so much for this patch! I couldn't use everything as the codebase had changed a bit but it saved me a lot of time in getting everything working.

django-tenant-schemas 1.5.1 now supports Django 1.7. Please let me know if any of you have any problems. @tsalaet @richkirsch @bufke @tomturner

**Comment by bufke** [comment]
I have it working in my staging environment @bernardopires looks good so far.

**Comment by geovanisouza92** [comment]
I've tested here too. Works like a charm! Thanks.

**Comment by tpyo** [comment]
Working great.  Thanks for the hard work @owais @bernardopires.

**Comment by owais** [comment]
This is great! Thanks @bernardopires

**Comment by gam-phon** [comment]
Thank you. I was waiting for this ^_^

**Comment by tsalaet** [comment]
@bernardopires thanks! works perfect!

**Comment by hugotox** [comment]
+1 Big thanks!!!

**Pull request closed without merging**
