### PR TITLE
Drop support for Django < 1.8

### LINKED ISSUE #289: Multitenant templates for Django 1.8
Hello!

I am trying to use multitenant templates with django 1.8. However, in template_loaders.py you are using 3 methods from django.template.loader that seem to have been removed in django 1.8 (get_template_from_string definitely has been (https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#get-template-from-string), I can't find anything on the other 2). Do you plan on updating that?

Thanks!
Julia

### PR DESCRIPTION
**Pull request by goodtune**
- this change deliberately drops support for versions of Django prior to 1.8
 - this is based on patch by @tomturner in Pull Request #290

### CODE REVIEW

**Comment by bernardopires** [comment]
Please do not drop support for older versions.

**Comment by goodtune** [comment]
Versions of Django prior to 1.8 are no longer supported by the core team. Django 1.7 has been out of mainstream support for over 1 year, and out of extended support for 6 months.

Can you publish the support timeline for this project with regards to releases of Django?

What is the rationale for continuing to support older versions in HEAD? You can always create support branches if you really want to provide LTS for older Django releases.

https://www.djangoproject.com/download/#supported-versions

**Comment by bernardopires** [comment]
That's a fair point! I agree to follow the official Django support timeline and drop support for Django 1.7. Would you be interested in updating the code to remove the cases we have in place for Django 1.7? Thanks a lot!

**Comment by goodtune** [comment]
Already on it, will have an updated PR soon.

**Comment by goodtune** [comment]
@bernardopires are you satisfied with the PR? All tests pass.

**Comment by bernardopires** [comment]
Awesome clean up! Thanks for also updating the docs, this is a huge help!

**Comment by goodtune** [comment]
Any chance we'll see a release on pypi soon?

**Comment by bernardopires** [comment]
Released! Thank you so much for the patch!

**Comment by AGASS007** [comment]
hi,

I think these changes weren't shipped in the 1.6.0. The v1.6.0 git tag points to ffc8e09ca9ffd8d53424fa0f43b731955c2050a2 from march.

**Comment by bernardopires** [comment]
That's my bad, should be correct now

2016-05-30 14:00 GMT+02:00 Guillaume Andreu Sabater <
notifications@github.com>:

**Comment by AGASS007** [comment]
yay!

Cheers

**Pull request merged**
