### PR TITLE
Add management command to create tenant

### PR DESCRIPTION
**Pull request by gannetson**
This adds a create_tenant command.
You can either pass arguments like:
```
./manage.py create_tenant --schema-name=new_tenant --domain-url=newtenant.net
```
or without:
```
./manage.py create_tenant
```
It will then prompt you for input

### CODE REVIEW

**Comment by bernardopires** [comment]
Doesn't this assume the only required fields for tenants are the `schema_name` and the `domain_url`?

**Comment by gannetson** [comment]
True. We ourselves got more fields then that. 
What do you suggest for this? Inspect for required fields or specify them?

**Comment by bernardopires** [comment]
I'd inspect the model and allow all (even the non required ones) the fields to be specified through the command line. Throw an error if an invalid parameter (non-existing field on the model) is passed. Thanks for the patch!

**Comment by gannetson** [comment]
Updated the code to be more generic.
Could you review it @bernardopires. Maybe it needs more clean-up or documentation?

You could also have a peak at https://github.com/onepercentclub/django-tenant-extras
where we added some other features to tenant_schemas we need for our project and that might be useful for base repo too.

**Comment by gannetson** [comment]
@bernardopires do you have any remarks on this PR?

**Comment by tomturner** [comment]
FYI this might not work with Django 1.8

**Comment by tomturner** [comment]
It did work so in Django 1.8. I have added part of the 1.8 patch

**Comment by gannetson** [comment]
Hey all, I was a bit to busy with other projects.
I can only look into this in a couple of weeks or so.
We might have some other patches then as well.

**Pull request closed without merging**
