### PR TITLE
Django 1.8 Support

### PR DESCRIPTION
**Pull request by tomturner**
This is Django 1.8 support it also provides support for Django 1.7 etc

### CODE REVIEW

**Comment by brechmos** [comment]
Excited!

**Comment by flxfxp** [comment]
:+1: :+1: :+1: :+1:

**Comment by MiltonLn** [comment]
Thank you tom!

**Comment by tomturner** [comment]
So I have ran the test in 1.7.7 and 1.8 I had to commit a migration folder to fix an error

**Comment by tomturner** [comment]
Do you know when this will get merged?

**Comment by flxfxp** [comment]
that's probably up to @bernardopires

**Comment by tomturner** [comment]
@MiltonLn I will have a look. I have only tested my changes in python 2.7.
Thanks for testing it.

**Comment by tomturner** [comment]
I am aware of a problem with createsuperuser command. I will look at this in the next couple of days.

**Comment by MiltonLn** [comment]
Tom i will be grateful with you if you add some documentation on createsuperuser (when fixed) like you do with the create_tenant command, Thank you a lot!

**Comment by tomturner** [comment]
@MiltonLn Will do

**Comment by tomturner** [comment]
@MiltonLn Fixed the ``createsuperuser``however I have renamed it to ``create_tenant_superuser`` so that you can use ``createsuperuser`` on the public schema. I have updated the documentation let me know what you think.

**Comment by bufke** [comment]
+1
@bernardopires if any testing, maintenance help, unit tests, or beer money would be useful I'd be happy to help out.

**Comment by honur** [comment]
If anyone interested, I made tenant_command work for django 1.8 too (based on this pull request).

**Comment by tomturner** [comment]
It is a right pain that this pull request hasn't gone in.
I don't think the owner of the project wants to get involved any more so I am thinking of forking this project so it can be actively maintained.

**Comment by flxfxp** [comment]
I hope @bernardopires is still alive, his last activity was in March... Anyway, I'm down for forking @tomturner, let me know if you need help setting up hosting, docs, PyPI, etc.

**Comment by gannetson** [comment]
Hey all @tomturner and I met on DjangoCon Europe last week in Cardiff and we decided to start a new repository for this code:
https://github.com/onepercentclub/django-multi-tenancy
Feel free to fork it and fire pull requests. We would like to continue the good work @bernardopires started.

**Comment by honur** [comment]
Great to hear that! 
Once tom's changes are applied to the new repository I can fire my pull request

**Comment by brechmos** [comment]
So glad that the project will continue!

On Thu, Jun 11, 2015 at 9:21 AM, Hovhannes Nurijanyan <
notifications@github.com> wrote:

> Great to hear that!
> Once tom's changes are applied to the new repository I can fire my pull
> request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bernardopires/django-tenant-schemas/pull/260#issuecomment-111133499>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by MiltonLn** [comment]
Great to hear that guys, once tom's changes are pushed to django-multi-tenancy i will communicate it to my team, we are working in a few projects with this tool, thank you onepercentclub.

PS: i will be waiting the pip installation command and documentation updated, if can i help pls let me know it.

**Comment by tomturner** [comment]
I am creating a pure 1.8 fork at the moment I will let you know when it is ready to use. @brechmos wanted it to be able to use it on 1.6 however that is this project with my pull request. As I said the project I will work on will be pure 1.8 and above. Before I let people loss on project I adding an enhancement to allow multiple URL to the same tenant/schema. So this project will continue!

**Comment by brechmos** [comment]
I am just finishing moving my work to Django 1.8.  So, please don't do
anything special for me.  I am so glad this project is going to continue.
Thank you all.  The only thing that I was having problems with is using a
non User AUTH_USER_MODEL as it was throwing errors.

On Thu, Jun 11, 2015 at 12:07 PM, tomturner <notifications@github.com>
wrote:

> I am creating a pure 1.8 fork at the moment I will let you know when it is
> ready to use. @brechmos <https://github.com/brechmos> wanted it to be
> able to use it on 1.6 however that is this project with my pull request. As
> I said the project I will work on will be pure 1.8 and above. Before I let
> people loss on project I adding an enhancement to allow multiple URL to the
> same tenant/schema. So this project will continue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bernardopires/django-tenant-schemas/pull/260#issuecomment-111187123>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by tomturner** [comment]
I have fixed the auth model already

**Comment by brechmos** [comment]
I will test today.  You are awesome. Thanks!  Which should I pip install?
(the previous or the onepercentclub one?)


On Thu, Jun 11, 2015 at 12:56 PM, tomturner <notifications@github.com>
wrote:

> I have fixed the auth model already
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bernardopires/django-tenant-schemas/pull/260#issuecomment-111206191>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by tomturner** [comment]
It will be on my new project hopefully I will commit later tonight in about 3-4hr tine

**Comment by tomturner** [comment]
Work in progress on the new 1.8 only version https://github.com/tomturner/django-tenants/
I hope to have it on pip soon. Feel free to test it and send pull requests.

I will not be working on django-multi-tenancy as @gannetson wanted to make it work for Django 1.6 and above.

**Comment by brechmos** [comment]
Hey @tomturner, have you had a chance to commit the AUTH_USER_MODEL fixes?
(and is that going to be to https://github.com/tomturner/django-tenants/)?

Thanks..

On Thu, Jun 11, 2015 at 12:59 PM, tomturner <notifications@github.com>
wrote:

> It will be on my new project hopefully I will commit later tonight in
> about 3-4hr tine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bernardopires/django-tenant-schemas/pull/260#issuecomment-111206907>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by tomturner** [comment]
Our new Django 1.8 only version is at https://github.com/tomturner/django-tenants and you can pip install django-tenants

**Comment by flxfxp** [comment]
Very exciting Tom, thank you for all your hard work. Let me know if you need any help :+1:

**Comment by honur** [comment]
Hi @tomturner. I noticed you modified the tenant_model, so wondering will there be any migration steps documented ?

**Comment by tomturner** [comment]
Hi @honur I did change the tenant model to allow for multiple url to the same tenant. I will try and document the process of upgrading however I haven't had to do it my self.

**Comment by MikeSmith12222** [comment]
Hi guys,

I just ran into the django 1.8 installation error this pull-request is about to fix.

I am really new to pip and stuff - so my question is:
**How do I install this version via pip to my virtualenv? Can anyone please give me a hint? :-) **

Thanks in advance! And thanks for the work!

**Comment by bernardopires** [comment]
Added support for django 1.8. Thanks @tomturner.

**Pull request closed without merging**
