### PR TITLE
Fixes #360

### LINKED ISSUE #360: Regression introduced in pull request #342
Apologies for introducing this, I didn't pay careful enough attention to the code I pulled in from @tomturner and hadn't realised this little change that snuck in...

https://github.com/bernardopires/django-tenant-schemas/commit/cb8862d026750a5543867e246c0e8de09b21c4fa?diff=unified#diff-9f78d9f30e7f0ad6094bba6ad1ba358eL100

There obviously wasn't a test case for this, but it has bitten me when I've upgraded my site using this... I lost all my custom templating.

New PR will follow shortly to address the regression.

### PR DESCRIPTION
**Pull request by goodtune**
Fix regression introduced in cb8862d

 - path construction changed from domain_url to schema_name

### CODE REVIEW

**Comment by bernardopires** [comment]
I'm confused, why should it be `domain_url` ?

**Comment by goodtune** [comment]
The original implementation in 0fcf1b9 chose `domain_url` and cb8862d broke that.

The rationale for `domain_url` is more or less arbitrary, but the reason for this PR is that it resolves the regression.

**Comment by goodtune** [comment]
I should also add that the documentation states that `%s` will be interpolated using the value of `tenant.domain_url` – so this brings the implementation back in line with the documentation and the historical design choice.

There may be good reasons for using the `schema_name` instead (the `schema_name` is unlikely to change while the `domain_url` is more likely to be altered). I will work on this in a separate PR by providing an alternate template loader class.

**Comment by goodtune** [comment]
@bernardopires do you want some more information or do you disagree that this is a regression?

**Comment by goodtune** [comment]
@bernardopires I am happy to assist with reviewing/merging pull requests and development on this library, I use it often, if you are willing to open control up?

**Comment by bernardopires** [comment]
Hi Gary, I'm really sorry, I promise I'll look into this latest at the weekend! I recently relocated to a new country and to a new apartment two weeks ago so things have been more busy than usual for me. I promise I'll also look into opening it to more people to contribute, that's probably a good idea as well. Thanks for the patch and the support! :-)

**Pull request merged**
