### PR TITLE
Add UUIDField, some index introspections and fix migrations performance issue

### PR DESCRIPTION
**Pull request by mcanaves**
- Added introspection support for UUIDField.
- Added index order introspection.
- Added index type introspection.
- Allowed introspection to work regardless of table owner.
- Added introspection for expression-based index.
- Fix performance issue when querying constraint_column_usage.

### CODE REVIEW

**Comment by AGASS007** [comment]
See #384

**Comment by mcanaves** [comment]
@AGASS007 both solve the same problem but with two different approaches. Sincerely I think the approach used in my pull request, from django postgres instropection, is better.

**Existing query**
```
Sort  (cost=282433.70..282433.71 rows=1 width=256) (actual time=4704.228..4704.228 rows=10 loops=1)
  Sort Key: ((((information_schema._pg_expandarray(c.conkey))).n)::information_schema.cardinal_number)
  Sort Method: quicksort  Memory: 27kB
  ->  Nested Loop  (cost=1.27..282433.69 rows=1 width=256) (actual time=590.133..4704.208 rows=10 loops=1)
        ->  Nested Loop  (cost=0.84..139352.49 rows=20 width=200) (actual time=135.518..294.376 rows=10 loops=1)
              Join Filter: (((c.conname)::information_schema.sql_identifier)::text = ("*SELECT* 1".constraint_name)::text)
              Rows Removed by Join Filter: 230
              ->  Nested Loop  (cost=0.42..35603.18 rows=1000 width=223) (actual time=67.594..99.859 rows=10 loops=1)
                    Join Filter: (c.connamespace = nc.oid)
                    Rows Removed by Join Filter: 15310
                    ->  Nested Loop  (cost=0.42..35542.46 rows=1 width=227) (actual time=67.468..97.118 rows=10 loops=1)
                          ->  Nested Loop  (cost=0.00..35510.04 rows=2 width=136) (actual time=67.452..97.072 rows=1 loops=1)
                                Join Filter: (nr.oid = r.relnamespace)
                                Rows Removed by Join Filter: 1525
                                ->  Seq Scan on pg_class r  (cost=0.00..35427.50 rows=463 width=76) (actual time=66.575..95.863 rows=1526 loops=1)
                                      Filter: ((relkind = 'r'::"char") AND (((relname)::information_schema.sql_identifier)::text = 'txdengine_factura'::text))
                                      Rows Removed by Filter: 541188
                                ->  Materialize  (cost=0.00..47.84 rows=5 width=68) (actual time=0.000..0.001 rows=1 loops=1526)
                                      ->  Seq Scan on pg_namespace nr  (cost=0.00..47.81 rows=5 width=68) (actual time=0.017..0.789 rows=1 loops=1)
                                            Filter: ((NOT pg_is_other_temp_schema(oid)) AND (((nspname)::information_schema.sql_identifier)::text = 'aaron453c57d76e6b'::text))
                                            Rows Removed by Filter: 1531
                          ->  Index Scan using pg_constraint_conrelid_index on pg_constraint c  (cost=0.42..16.17 rows=4 width=95) (actual time=0.012..0.035 rows=10 loops=1)
                                Index Cond: (conrelid = r.oid)
                                Filter: (contype = ANY ('{p,u,f}'::"char"[]))
                                Rows Removed by Filter: 1
                    ->  Seq Scan on pg_namespace nc  (cost=0.00..36.32 rows=1532 width=4) (actual time=0.002..0.145 rows=1532 loops=10)
              ->  Materialize  (cost=0.42..103669.32 rows=4 width=128) (actual time=6.792..19.445 rows=24 loops=10)
                    ->  Append  (cost=0.42..103669.30 rows=4 width=128) (actual time=67.919..194.429 rows=24 loops=1)
                          ->  Subquery Scan on "*SELECT* 1"  (cost=0.42..51853.42 rows=1 width=128) (actual time=67.919..100.556 rows=11 loops=1)
                                ->  Nested Loop  (cost=0.42..51853.41 rows=1 width=193) (actual time=67.918..100.552 rows=11 loops=1)
                                      Join Filter: (c_1.connamespace = nc_1.oid)
                                      Rows Removed by Join Filter: 16841
                                      ->  Nested Loop  (cost=0.42..51797.92 rows=1 width=197) (actual time=67.906..98.282 rows=11 loops=1)
                                            ->  Nested Loop  (cost=0.00..51781.19 rows=1 width=132) (actual time=67.892..98.257 rows=1 loops=1)
                                                  Join Filter: (nr_1.oid = r_1.relnamespace)
                                                  Rows Removed by Join Filter: 1525
                                                  ->  Seq Scan on pg_class r_1  (cost=0.00..51708.92 rows=326 width=72) (actual time=67.269..97.315 rows=1526 loops=1)
                                                        Filter: ((relkind = 'r'::"char") AND (((relname)::information_schema.sql_identifier)::text = 'txdengine_factura'::text) AND (pg_has_role(relowner, 'USAGE'::text) OR has_table_privilege(oid, 'INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER'::text) OR has_any_column_privilege(oid, 'INSERT, UPDATE, REFERENCES'::text)))
                                                        Rows Removed by Filter: 541188
                                                  ->  Materialize  (cost=0.00..47.84 rows=5 width=68) (actual time=0.000..0.000 rows=1 loops=1526)
                                                        ->  Seq Scan on pg_namespace nr_1  (cost=0.00..47.81 rows=5 width=68) (actual time=0.013..0.551 rows=1 loops=1)
                                                              Filter: ((NOT pg_is_other_temp_schema(oid)) AND (((nspname)::information_schema.sql_identifier)::text = 'aaron453c57d76e6b'::text))
                                                              Rows Removed by Filter: 1531
                                            ->  Index Scan using pg_constraint_conrelid_index on pg_constraint c_1  (cost=0.42..16.69 rows=4 width=73) (actual time=0.011..0.019 rows=11 loops=1)
                                                  Index Cond: (conrelid = r_1.oid)
                                                  Filter: (contype <> ALL ('{t,x}'::"char"[]))
                                      ->  Seq Scan on pg_namespace nc_1  (cost=0.00..36.32 rows=1532 width=4) (actual time=0.001..0.123 rows=1532 loops=11)
                          ->  Subquery Scan on "*SELECT* 2"  (cost=0.43..51815.88 rows=3 width=128) (actual time=65.851..93.871 rows=13 loops=1)
                                ->  Nested Loop  (cost=0.43..51815.85 rows=3 width=138) (actual time=65.851..93.869 rows=13 loops=1)
                                      ->  Nested Loop  (cost=0.00..51781.19 rows=1 width=136) (actual time=65.825..93.824 rows=1 loops=1)
                                            Join Filter: (nr_2.oid = r_2.relnamespace)
                                            Rows Removed by Join Filter: 1525
                                            ->  Seq Scan on pg_class r_2  (cost=0.00..51708.92 rows=326 width=72) (actual time=65.236..92.957 rows=1526 loops=1)
                                                  Filter: ((relkind = 'r'::"char") AND (((relname)::information_schema.sql_identifier)::text = 'txdengine_factura'::text) AND (pg_has_role(relowner, 'USAGE'::text) OR has_table_privilege(oid, 'INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER'::text) OR has_any_column_privilege(oid, 'INSERT, UPDATE, REFERENCES'::text)))
                                                  Rows Removed by Filter: 541188
                                            ->  Materialize  (cost=0.00..47.84 rows=5 width=68) (actual time=0.000..0.000 rows=1 loops=1526)
                                                  ->  Seq Scan on pg_namespace nr_2  (cost=0.00..47.81 rows=5 width=68) (actual time=0.014..0.524 rows=1 loops=1)
                                                        Filter: ((NOT pg_is_other_temp_schema(oid)) AND (((nspname)::information_schema.sql_identifier)::text = 'aaron453c57d76e6b'::text))
                                                        Rows Removed by Filter: 1531
                                      ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a_1  (cost=0.43..34.45 rows=12 width=6) (actual time=0.011..0.019 rows=13 loops=1)
                                            Index Cond: ((attrelid = r_2.oid) AND (attnum > 0))
                                            Filter: (attnotnull AND (NOT attisdropped))
                                            Rows Removed by Filter: 13
        ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a  (cost=0.43..8.21 rows=1 width=70) (actual time=0.011..0.012 rows=1 loops=10)
              Index Cond: ((attrelid = r.oid) AND (attnum = ((information_schema._pg_expandarray(c.conkey))).x))
              Filter: ((NOT attisdropped) AND (pg_has_role(r.relowner, 'USAGE'::text) OR has_column_privilege(r.oid, attnum, 'SELECT, INSERT, UPDATE, REFERENCES'::text)))
        SubPlan 1
          ->  Result  (cost=16407.27..142916.69 rows=684601 width=128) (actual time=231.378..440.960 rows=1 loops=10)
                ->  Append  (cost=16407.27..136070.68 rows=684601 width=128) (actual time=231.375..440.956 rows=1 loops=10)
                      ->  Subquery Scan on "*SELECT* 1_1"  (cost=16407.27..16407.29 rows=1 width=128) (actual time=40.896..40.896 rows=0 loops=10)
                            ->  HashAggregate  (cost=16407.27..16407.28 rows=1 width=324) (actual time=40.893..40.893 rows=0 loops=10)
                                  Group Key: nr_3.nspname, r_3.relname, r_3.relowner, a_2.attname, nc_2.nspname, c_2.conname
                                  ->  Nested Loop  (cost=1.28..16407.25 rows=1 width=324) (actual time=40.892..40.892 rows=0 loops=10)
                                        Join Filter: (c_2.connamespace = nc_2.oid)
                                        ->  Nested Loop  (cost=1.28..16351.78 rows=1 width=264) (actual time=40.891..40.891 rows=0 loops=10)
                                              Join Filter: (r_3.oid = a_2.attrelid)
                                              ->  Nested Loop  (cost=0.85..16350.60 rows=1 width=212) (actual time=40.890..40.890 rows=0 loops=10)
                                                    Join Filter: (r_3.relnamespace = nr_3.oid)
                                                    ->  Seq Scan on pg_namespace nr_3  (cost=0.00..47.81 rows=8 width=68) (actual time=0.004..0.300 rows=1 loops=10)
                                                          Filter: (((nspname)::information_schema.sql_identifier)::text = ((nr.nspname)::information_schema.sql_identifier)::text)
                                                          Rows Removed by Filter: 1531
                                                    ->  Materialize  (cost=0.85..16302.55 rows=2 width=152) (actual time=40.588..40.588 rows=0 loops=10)
                                                          ->  Nested Loop  (cost=0.85..16302.54 rows=2 width=152) (actual time=40.587..40.587 rows=0 loops=10)
                                                                ->  Nested Loop  (cost=0.43..16275.78 rows=36 width=76) (actual time=40.586..40.586 rows=0 loops=10)
                                                                      ->  Seq Scan on pg_constraint c_2  (cost=0.00..15260.28 rows=120 width=72) (actual time=40.585..40.585 rows=0 loops=10)
                                                                            Filter: ((contype = 'c'::"char") AND (((conname)::information_schema.sql_identifier)::text = ((c.conname)::information_schema.sql_identifier)::text))
                                                                            Rows Removed by Filter: 304114
                                                                      ->  Index Scan using pg_depend_depender_index on pg_depend d  (cost=0.43..8.45 rows=1 width=12) (never executed)
                                                                            Index Cond: ((classid = '2606'::oid) AND (objid = c_2.oid))
                                                                            Filter: (refclassid = '1259'::oid)
                                                                ->  Index Scan using pg_class_oid_index on pg_class r_3  (cost=0.42..0.73 rows=1 width=76) (never executed)
                                                                      Index Cond: (oid = d.refobjid)
                                                                      Filter: (pg_has_role(relowner, 'USAGE'::text) AND (relkind = 'r'::"char"))
                                              ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a_2  (cost=0.43..1.17 rows=1 width=70) (never executed)
                                                    Index Cond: ((attrelid = d.refobjid) AND (attnum = d.refobjsubid))
                                                    Filter: (NOT attisdropped)
                                        ->  Seq Scan on pg_namespace nc_2  (cost=0.00..36.32 rows=1532 width=68) (never executed)
                      ->  Subquery Scan on "*SELECT* 2_1"  (cost=103.81..119663.40 rows=684600 width=128) (actual time=190.477..400.057 rows=1 loops=10)
                            ->  Nested Loop  (cost=103.81..112817.40 rows=684600 width=128) (actual time=190.476..400.055 rows=1 loops=10)
                                  Join Filter: CASE WHEN (c_3.contype = 'f'::"char") THEN ((r_4.oid = c_3.confrelid) AND (a_3.attnum = ANY (c_3.confkey))) ELSE ((r_4.oid = c_3.conrelid) AND (a_3.attnum = ANY (c_3.conkey))) END
                                  Rows Removed by Join Filter: 1205460
                                  ->  Hash Join  (cost=55.47..15715.14 rows=1400 width=55) (actual time=30.503..76.833 rows=1526 loops=10)
                                        Hash Cond: (c_3.connamespace = nc_3.oid)
                                        ->  Seq Scan on pg_constraint c_3  (cost=0.00..15640.42 rows=1400 width=59) (actual time=30.461..76.036 rows=1526 loops=10)
                                              Filter: ((contype = ANY ('{p,u,f}'::"char"[])) AND (((conname)::information_schema.sql_identifier)::text = ((c.conname)::information_schema.sql_identifier)::text))
                                              Rows Removed by Filter: 302588
                                        ->  Hash  (cost=36.32..36.32 rows=1532 width=4) (actual time=0.349..0.349 rows=1532 loops=1)
                                              Buckets: 2048  Batches: 1  Memory Usage: 70kB
                                              ->  Seq Scan on pg_namespace nc_3  (cost=0.00..36.32 rows=1532 width=4) (actual time=0.005..0.172 rows=1532 loops=1)
                                  ->  Materialize  (cost=48.34..35490.70 rows=978 width=134) (actual time=0.000..0.132 rows=790 loops=15259)
                                        ->  Nested Loop  (cost=48.34..35485.81 rows=978 width=134) (actual time=0.500..159.288 rows=790 loops=10)
                                              ->  Hash Join  (cost=47.91..34236.05 rows=161 width=68) (actual time=0.484..158.860 rows=58 loops=10)
                                                    Hash Cond: (r_4.relnamespace = nr_4.oid)
                                                    ->  Seq Scan on pg_class r_4  (cost=0.00..34070.71 rows=30886 width=72) (actual time=0.009..153.099 rows=88693 loops=10)
                                                          Filter: (pg_has_role(relowner, 'USAGE'::text) AND (relkind = 'r'::"char"))
                                                          Rows Removed by Filter: 454021
                                                    ->  Hash  (cost=47.81..47.81 rows=8 width=4) (actual time=0.285..0.285 rows=1 loops=10)
                                                          Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                                          ->  Seq Scan on pg_namespace nr_4  (cost=0.00..47.81 rows=8 width=4) (actual time=0.006..0.283 rows=1 loops=10)
                                                                Filter: (((nspname)::information_schema.sql_identifier)::text = ((nr.nspname)::information_schema.sql_identifier)::text)
                                                                Rows Removed by Filter: 1531
                                              ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a_3  (cost=0.43..7.52 rows=24 width=70) (actual time=0.003..0.006 rows=14 loops=580)
                                                    Index Cond: (attrelid = r_4.oid)
                                                    Filter: (NOT attisdropped)
```
**_Planning time: 2.682 ms
Execution time: 4704.509 ms_**

**New query**
```
Nested Loop  (cost=1.12..140.69 rows=1 width=119) (actual time=0.082..0.262 rows=11 loops=1)
  ->  Nested Loop  (cost=0.70..16.75 rows=1 width=4) (actual time=0.018..0.019 rows=1 loops=1)
        ->  Index Scan using pg_namespace_nspname_index on pg_namespace ns  (cost=0.28..8.29 rows=1 width=4) (actual time=0.009..0.009 rows=1 loops=1)
              Index Cond: (nspname = 'aaron453c57d76e6b'::name)
        ->  Index Scan using pg_class_relname_nsp_index on pg_class cl  (cost=0.42..8.45 rows=1 width=8) (actual time=0.008..0.009 rows=1 loops=1)
              Index Cond: ((relname = 'txdengine_factura'::name) AND (relnamespace = ns.oid))
  ->  Index Scan using pg_constraint_conrelid_index on pg_constraint c  (cost=0.42..17.77 rows=4 width=119) (actual time=0.006..0.009 rows=11 loops=1)
        Index Cond: (conrelid = cl.oid)
  SubPlan 1
    ->  Sort  (cost=88.92..89.22 rows=120 width=68) (actual time=0.014..0.014 rows=1 loops=11)
          Sort Key: cols.arridx
          Sort Method: quicksort  Memory: 25kB
          ->  Hash Join  (cost=27.94..84.78 rows=120 width=68) (actual time=0.011..0.013 rows=1 loops=11)
                Hash Cond: (ca.attnum = cols.colid)
                ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute ca  (cost=0.43..53.00 rows=24 width=66) (actual time=0.002..0.006 rows=32 loops=11)
                      Index Cond: (attrelid = c.conrelid)
                ->  Hash  (cost=15.01..15.01 rows=1000 width=6) (actual time=0.002..0.002 rows=1 loops=11)
                      Buckets: 1024  Batches: 1  Memory Usage: 9kB
                      ->  Subquery Scan on cols  (cost=0.00..15.01 rows=1000 width=6) (actual time=0.001..0.002 rows=1 loops=11)
                            ->  Result  (cost=0.00..5.01 rows=1000 width=0) (actual time=0.001..0.002 rows=1 loops=11)
  SubPlan 2
    ->  Nested Loop  (cost=0.85..16.91 rows=1 width=128) (actual time=0.004..0.005 rows=1 loops=11)
          ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute fka  (cost=0.43..8.45 rows=1 width=68) (actual time=0.002..0.002 rows=1 loops=11)
                Index Cond: ((attrelid = c.confrelid) AND (attnum = (c.confkey)[1]))
          ->  Index Scan using pg_class_oid_index on pg_class fkc  (cost=0.42..8.44 rows=1 width=68) (actual time=0.002..0.002 rows=1 loops=9)
                Index Cond: (oid = c.confrelid)
```
_**Planning time: 0.298 ms
Execution time: 0.329 ms**_

**Comment by AGASS007** [comment]
@mcanaves that was precisely my point ;) But I agree that I should have made clearer that I referenced the other PR because they address the same issue, and not because your patch has subsequently become stale.

**Comment by AGASS007** [comment]
When you say __Existing query__, are you referencing the query pre or post #384 ?

**Comment by mcanaves** [comment]
The query after ;).

**Comment by AGASS007** [comment]
wow. ok.

**Comment by AGASS007** [comment]
Someone willing/able to review this thoroughly? @tonioo?

**Comment by tonioo** [comment]
@AGASS007 @mcanaves Looks like your approach is indeed better, nothing more to say about this.
Maybe it would be better to split your modifications into several pull requests ? Easier to review and accept from my point of view.

**Comment by bernardopires** [comment]
Thanks for the awesome patch!

**Comment by JakeMana** [comment]
is there any progress on this? Im looking for this kind of fix...Im using UUID in all models so it would be great to have it here as well

**Pull request merged**
